import pandas as pd
df=pd.read_csv('ZILLOW-Z77006_ZRIMFRR.csv')
##print(df.head())
df.set_index('Date',inplace=True)
##print(df.head())
df.to_csv('newcsv2.csv')
##df=pd.read_csv('newcsv2.csv')
##print(df.head())
df=pd.read_csv('newcsv2.csv',index_col=0)
##print(df.head())
df.columns=['House_Prices']
##print(df.head())
df.to_csv('newcsv3.csv',header=False)
##df.to_html('example.html')
df=pd.read_csv('newcsv3.csv',names=['Date','House_Prices'])
#print(df.head())
df.rename(columns={'House_Prices':'HPI'},inplace=True)
print(df.head())
